config/routes.rb
Rails.application.routes.draw do
  resources :passages

end

app/models/passage.rb
class Passage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_action :set_passage, only: [:show, :edit, :update, :destroy]

  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
  end

  # GET /passages/new
  def new
    @passage = Passage.new
  end

  # GET /passages/1/edit
  def edit
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(passage_params)

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render :show, status: :created, location: @passage }
      else
        format.html { render :new }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passages/1
  # PATCH/PUT /passages/1.json
  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { render :show, status: :ok, location: @passage }
      else
        format.html { render :edit }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url, notice: 'Passage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passage
      @passage = Passage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passage_params
      params.require(:passage).permit(:name, :passage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passage.errors.count, "error") %> prohibited this passage from being saved:</h2>

      <ul>
      <% @passage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :passage %><br>
    <%= f.text_area :passage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passages/edit.html.erb
<h1>Editing Passage</h1>

<%= render 'form' %>

<%= link_to 'Show', @passage %> |
<%= link_to 'Back', passages_path %>

app/views/passages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Passages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Passage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passages.each do |passage| %>
      <tr>
        <td><%= passage.name %></td>
        <td><%= passage.passage %></td>
        <td><%= link_to 'Show', passage %></td>
        <td><%= link_to 'Edit', edit_passage_path(passage) %></td>
        <td><%= link_to 'Destroy', passage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passage', new_passage_path %>

app/views/passages/new.html.erb
<h1>New Passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>

app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passage.name %>
</p>

<p>
  <div id="passage"></div>
</p>

<div>
  <textarea id="textarea" rows="4" cols="50">
  </textarea>
</div>

<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>
<script type="text/javascript">
  $( document ).ready(function() {
    $('#textarea').text("");
    var passage = "<%= @passage.passage %>";
    console.log(passage);
  $('#textarea').bind('input propertychange', function() {
      var text_input = $("#textarea").val();
      var text_input_length = text_input.length;
      if (text_input == passage.substring(0,text_input_length)){
        $("#passage").text(text_input);
        if (text_input.length == passage.length){
          setInterval(function(){passage_complete()},200);
        }
      }else {
        alert("You got something wrong");
      }
});
});
  function passage_complete() {
    alert("Great Job, you memorized the passage.");
    location.reload();
  }
</script>